# Generated by Django 3.0.7 on 2020-07-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mshare', '0004_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='owner',
            new_name='author',
        ),
    ]
